[supervisord]
nodaemon=true
environment=PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin,TZ='UTC0'
logfile=/tmp/supervisord.log
pidfile=/tmp/supervisord.pid

[program:hdfs-datanode]
command=/lib/sbin/hdfs-datanode.sh
stdout_logfile=/tmp/hdfs-datanode.out.log
stderr_logfile=/tmp/hdfs-datanode.err.log
autorestart=true
startsecs=10
user=hdfs
