[supervisord]
nodaemon=true
environment=PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin,TZ='UTC0'
logfile=/tmp/supervisord.log
pidfile=/tmp/supervisord.pid

[inet_http_server]
port=0.0.0.0:9001
username=supervisord
password=supervisord@password

[program:hdfs-namenode]
command=/lib/sbin/hdfs-namenode.sh
stdout_logfile=/tmp/hdfs-namenode.out.log
stderr_logfile=/tmp/hdfs-namenode.err.log
autorestart=true
startsecs=10
user=hdfs

[program:hdfs-secondarynamenode]
command=/lib/sbin/hdfs-secondarynamenode.sh
stdout_logfile=/tmp/hdfs-secondarynamenode.out.log
stderr_logfile=/tmp/hdfs-secondarynamenode.err.log
autorestart=true
startsecs=10
user=hdfs

[program:hdfs-datanode]
command=/lib/sbin/hdfs-datanode.sh
stdout_logfile=/tmp/hdfs-datanode.out.log
stderr_logfile=/tmp/hdfs-datanode.err.log
autorestart=true
startsecs=10
user=hdfs

[program:hive-metastore]
command=/lib/sbin/hive-metastore.sh
stdout_logfile=/tmp/hive-metastore.log
stderr_logfile=/tmp/hive-metastore.log
autorestart=true
startsecs=10
user=hive

[program:spark-thriftserver]
command=/lib/sbin/spark-thriftserver.sh
stdout_logfile=/tmp/spark-thriftserver.log
stderr_logfile=/tmp/spark-thriftserver.log
autorestart=true
startsecs=10
user=hadoop


[program:trino]
command=/lib/sbin/trino.sh
stdout_logfile=/tmp/trino.log
stderr_logfile=/tmp/trino.log
autorestart=true
startsecs=10
user=trino

[program:airflow]
command=/lib/sbin/airflow.sh
directory=/home/hadoop/projects/chainslake/airflow
stdout_logfile=/tmp/airflow.log
stderr_logfile=/tmp/airflow.log
autorestart=true
startsecs=10
user=hadoop